/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gate */
        get: operations["gate_api_gate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gate/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gate History */
        get: operations["gate_history_api_gate_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model */
        get: operations["model_api_model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Versions */
        get: operations["model_versions_api_model_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/coefficients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coefficients */
        get: operations["coefficients_api_model_coefficients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decisions */
        get: operations["decisions_api_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily */
        get: operations["daily_api_decisions_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage */
        get: operations["coverage_api_decisions_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invoices */
        get: operations["invoices_api_invoices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invoice */
        get: operations["invoice_api_invoices__invoice_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sim Status */
        get: operations["sim_status_api_sim_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sim/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sim Step */
        post: operations["sim_step_api_sim_step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sim/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sim Score */
        get: operations["sim_score_api_sim_score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiError */
        ApiError: {
            /** Detail */
            detail: string;
        };
        /** AttemptRow */
        AttemptRow: {
            /** Attempt Index */
            attempt_index: number;
            /** Attempted At */
            attempted_at: string;
            /** Delay Hours */
            delay_hours: number;
            /** Dt Bucket */
            dt_bucket: number;
            /** Success */
            success: boolean;
            /** Disputed */
            disputed: boolean;
        };
        /** BucketInfo */
        BucketInfo: {
            /** Bucket */
            bucket: number;
            /** Label */
            label: string;
            /** Lo H */
            lo_h: number;
            /** Hi H */
            hi_h: number;
        };
        /** Coefficient */
        Coefficient: {
            /**
             * Part
             * @enum {string}
             */
            part: "hazard" | "cure";
            /** Term */
            term: string;
            /** Coef */
            coef: number;
            /** Se */
            se: number;
        };
        /** Coverage */
        Coverage: {
            /** Buckets */
            buckets: components["schemas"]["BucketInfo"][];
            /** Ladder Bucket */
            ladder_bucket: number | null;
            /**
             * By Mode
             * @description share of first-retry decisions per bucket, per logging mode
             */
            by_mode: {
                [key: string]: number[];
            };
            /** N By Mode */
            n_by_mode: {
                [key: string]: number;
            };
        };
        /** CurvePoint */
        CurvePoint: {
            /** Bucket */
            bucket: number;
            /** Label */
            label: string;
            /** Delay H */
            delay_h: number;
            /**
             * Value Usd
             * @description schedule value if this bucket goes first
             */
            value_usd: number | null;
            /** Propensity */
            propensity: number;
            /** Viable */
            viable: boolean;
        };
        /** DailyCount */
        DailyCount: {
            /** Day */
            day: string;
            /** Policy */
            policy: string;
            /** N */
            n: number;
        };
        /** DecisionPage */
        DecisionPage: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Rows */
            rows: components["schemas"]["DecisionRow"][];
            /**
             * Facets
             * @description counts per value of mode / policy / action over the filtered set
             */
            facets: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /** DecisionRow */
        DecisionRow: {
            /** Decision Id */
            decision_id: string;
            /** Decided At */
            decided_at: string;
            /** Decided At H */
            decided_at_h: number;
            /** Invoice Id */
            invoice_id: string;
            /** Attempt Index */
            attempt_index: number;
            /** Action */
            action: string;
            /** Delay Hours */
            delay_hours: number | null;
            /** Execute At H */
            execute_at_h: number | null;
            /** Dt Bucket */
            dt_bucket: number | null;
            /** Propensity */
            propensity: number | null;
            /** Mode */
            mode: string;
            /** Policy */
            policy: string;
            /** Model Version */
            model_version: string | null;
            /** P Gone */
            p_gone: number | null;
            /** P Success */
            p_success: number | null;
            /** Expected Value Usd */
            expected_value_usd: number | null;
            /** Rationale */
            rationale: string | null;
        };
        /**
         * Explanation
         * @description The planner's *best* plan for this invoice (no exploration), plus the
         *     Thompson distribution it samples the logged action from. The logged
         *     decision can differ from ``delay_hours`` -- that is exploration.
         */
        Explanation: {
            /**
             * As Of
             * @enum {string}
             */
            as_of: "now" | "at_failure";
            /** Attempt Index */
            attempt_index: number;
            /** Action */
            action: string;
            /** Rationale */
            rationale: string;
            /** P Gone */
            p_gone: number;
            /**
             * P Success
             * @description P(success) of the best schedule's first attempt
             */
            p_success: number;
            /**
             * Expected Value Usd
             * @description value of the best schedule
             */
            expected_value_usd: number;
            /**
             * Delay Hours
             * @description best first delay, hours since failure
             */
            delay_hours: number | null;
            /** Best Bucket */
            best_bucket: number | null;
            /** Schedule H */
            schedule_h: number[];
            /**
             * Explore Mass
             * @description probability the logged action is NOT the best bucket
             * @default 0
             */
            explore_mass: number;
            /** Curve */
            curve: components["schemas"]["CurvePoint"][];
            /** Model Version */
            model_version: string;
        };
        /** GateHistoryPoint */
        GateHistoryPoint: {
            /** Generated At */
            generated_at: string;
            /** Data As Of */
            data_as_of: string | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "HOLD" | "SWITCH";
            /** Delta */
            delta: number | null;
            /** Lo */
            lo: number | null;
            /** Hi */
            hi: number | null;
            /** Ess */
            ess: number | null;
            /** N Logged */
            n_logged: number | null;
        };
        /** GateStatus */
        GateStatus: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "HOLD" | "SWITCH";
            /** Reason */
            reason: string;
            /**
             * On File
             * @description False when no gate has run yet (treated as HOLD)
             */
            on_file: boolean;
            /** Generated At */
            generated_at: string | null;
            /** Data As Of */
            data_as_of: string | null;
            /** Window Start */
            window_start: string | null;
            /** Model Version */
            model_version: string | null;
            /** Previous */
            previous: string | null;
            /**
             * Delta
             * @description DR(planner) - DR(ladder), USD/invoice
             */
            delta: number | null;
            /** Lo */
            lo: number | null;
            /** Hi */
            hi: number | null;
            /** Ess */
            ess: number | null;
            /** Min Ess */
            min_ess: number | null;
            /** Dr Planner */
            dr_planner: number | null;
            /** Dr Incumbent */
            dr_incumbent: number | null;
            /** N Logged */
            n_logged: number | null;
            /** Logged By Mode */
            logged_by_mode: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
            /** Synthetic */
            synthetic: boolean;
            /** Data As Of */
            data_as_of: string | null;
            /** Has Model */
            has_model: boolean;
            /** Has Gate */
            has_gate: boolean;
            paths: components["schemas"]["Paths"];
        };
        /** Holdout */
        Holdout: {
            /** Pr Auc */
            pr_auc: number;
            /** Roc Auc */
            roc_auc: number;
            /** Log Loss */
            log_loss: number;
            /** Ece */
            ece: number;
            /** Base Rate */
            base_rate: number;
            /** N Test Attempts */
            n_test_attempts: number;
        };
        /** InvoiceDetail */
        InvoiceDetail: {
            invoice: components["schemas"]["InvoiceRow"];
            /** Customer Tenure Days */
            customer_tenure_days: number | null;
            /** Prior Successful Payments */
            prior_successful_payments: number;
            /** Active In Window */
            active_in_window: boolean;
            /** Plan Tier */
            plan_tier: string;
            /** Attempts */
            attempts: components["schemas"]["AttemptRow"][];
            /** Decisions */
            decisions: components["schemas"]["DecisionRow"][];
            explanation: components["schemas"]["Explanation"] | null;
            /** Explanation Error */
            explanation_error: string | null;
        };
        /** InvoicePage */
        InvoicePage: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Rows */
            rows: components["schemas"]["InvoiceRow"][];
        };
        /** InvoiceRow */
        InvoiceRow: {
            /** Invoice Id */
            invoice_id: string;
            /** Merchant Id */
            merchant_id: string;
            /** Customer Id */
            customer_id: string;
            /** Market */
            market: string;
            /** Rail */
            rail: string;
            /** Decline Reason */
            decline_reason: string;
            /** Reason Class */
            reason_class: string;
            /** Network Advice */
            network_advice: string;
            /** Amount Usd */
            amount_usd: number;
            /** Fail Time H */
            fail_time_h: number;
            /** Failed At */
            failed_at: string;
            /** Elapsed H */
            elapsed_h: number;
            /** Attempts */
            attempts: number;
            /** Recovered */
            recovered: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "recovered" | "routed" | "closed";
            /** Next Action */
            next_action: string | null;
            /** Next Execute At H */
            next_execute_at_h: number | null;
            /** Next Policy */
            next_policy: string | null;
        };
        /** ModelSummary */
        ModelSummary: {
            /** Version */
            version: string;
            /** Trained At */
            trained_at: string;
            /** Data As Of */
            data_as_of: string;
            /** N Invoices */
            n_invoices: number;
            /** N Attempts */
            n_attempts: number;
            /** N Merchants */
            n_merchants: number;
            /** Success Rate */
            success_rate: number;
            /** Mean P Gone */
            mean_p_gone: number;
            /** Converged */
            converged: boolean;
            holdout: components["schemas"]["Holdout"] | null;
            /** Cure Labels */
            cure_labels: {
                [key: string]: unknown;
            };
            /** Fit Warnings */
            fit_warnings: string[];
            /** Dispute Base */
            dispute_base: {
                [key: string]: number;
            };
            /** Ladder H */
            ladder_h: number[];
            /** Unmapped Codes */
            unmapped_codes: {
                [key: string]: number;
            };
        };
        /** ModelVersion */
        ModelVersion: {
            /** Version */
            version: string;
            /** Current */
            current: boolean;
            /** Trained At */
            trained_at: string | null;
            /** Data As Of */
            data_as_of: string | null;
            /** Pr Auc */
            pr_auc: number | null;
            /** Mean P Gone */
            mean_p_gone: number | null;
        };
        /** Overview */
        Overview: {
            /** Data As Of */
            data_as_of: string;
            /** Synthetic */
            synthetic: boolean;
            gate: components["schemas"]["GateStatus"];
            model: components["schemas"]["ModelSummary"] | null;
            /** Open Invoices */
            open_invoices: number;
            /** Awaiting Decision */
            awaiting_decision: number;
            /**
             * Queued Retries
             * @description retries decided and not yet due
             */
            queued_retries: number;
            /** Decisions 24H */
            decisions_24h: number;
            /**
             * Explore Share 7D
             * @description share of retries decided in the last 7 days that were exploration
             */
            explore_share_7d: number | null;
            /** Invoices 30D */
            invoices_30d: number;
            /**
             * Recovered 30D
             * @description recovery rate of invoices whose window closed in the last 30 days
             */
            recovered_30d: number;
        };
        /** Paths */
        Paths: {
            /** Data */
            data: string;
            /** Models */
            models: string;
            /** Gate */
            gate: string;
            /** Audit */
            audit: string;
            /** Queue */
            queue: string;
        };
        /** PhaseScore */
        PhaseScore: {
            /** N */
            n: number;
            /** Realised */
            realised: number;
            /** Se */
            se: number;
            /** Ladder Oracle */
            ladder_oracle: number;
            /** Lift */
            lift: number | null;
        };
        /** Score */
        Score: {
            /** N Invoices */
            n_invoices: number;
            /** Note */
            note: string | null;
            /** Window */
            window: string[];
            /** Realised Per Invoice */
            realised_per_invoice: number | null;
            /** Realised Se */
            realised_se: number | null;
            /** Ladder Oracle Per Invoice */
            ladder_oracle_per_invoice: number | null;
            /** Lift Vs Ladder */
            lift_vs_ladder: number | null;
            /** Recovery Rate */
            recovery_rate: number | null;
            /** Attempts Per Invoice */
            attempts_per_invoice: number | null;
            /** By Mode */
            by_mode: {
                [key: string]: components["schemas"]["PhaseScore"];
            };
        };
        /** SimProgress */
        SimProgress: {
            /** Done */
            done: number;
            /** Total */
            total: number;
        };
        /** SimStatus */
        SimStatus: {
            /** Synthetic */
            synthetic: boolean;
            /** As Of */
            as_of: string | null;
            /** As Of H */
            as_of_h: number | null;
            /** Cutover */
            cutover: string | null;
            /** Cutover H */
            cutover_h: number | null;
            /** Horizon H */
            horizon_h: number | null;
            /**
             * Pending Events
             * @default 0
             */
            pending_events: number;
            /**
             * Busy
             * @default false
             */
            busy: boolean;
            progress: components["schemas"]["SimProgress"] | null;
            last_step: components["schemas"]["StepResult"] | null;
            /** Last Error */
            last_error: string | null;
        };
        /** StepRequest */
        StepRequest: {
            /**
             * Hours
             * @default 24
             */
            hours: number;
            /**
             * Plan
             * @description run the plan job before moving the clock
             * @default true
             */
            plan: boolean;
            /**
             * Explore Rate
             * @default 0.2
             */
            explore_rate: number;
        };
        /** StepResult */
        StepResult: {
            /** As Of */
            as_of: string;
            /** Steps */
            steps: number;
            /** Decisions */
            decisions: number;
            /** Released Failures */
            released_failures: number;
            /** Retries */
            retries: number;
            /** Recovered */
            recovered: number;
            /** Stale */
            stale: number;
            /** Seconds */
            seconds: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    gate_api_gate_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateStatus"];
                };
            };
        };
    };
    gate_history_api_gate_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateHistoryPoint"][];
                };
            };
        };
    };
    model_api_model_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSummary"] | null;
                };
            };
        };
    };
    model_versions_api_model_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelVersion"][];
                };
            };
        };
    };
    coefficients_api_model_coefficients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Coefficient"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    decisions_api_decisions_get: {
        parameters: {
            query?: {
                mode?: string | null;
                policy?: string | null;
                action?: string | null;
                invoice_id?: string | null;
                attempt_index?: number | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionPage"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    daily_api_decisions_daily_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyCount"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    coverage_api_decisions_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Coverage"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    invoices_api_invoices_get: {
        parameters: {
            query?: {
                status?: string | null;
                reason_class?: string | null;
                rail?: string | null;
                q?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoicePage"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    invoice_api_invoices__invoice_id__get: {
        parameters: {
            query?: {
                explain?: boolean;
            };
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    sim_status_api_sim_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimStatus"];
                };
            };
        };
    };
    sim_step_api_sim_step_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimStatus"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    sim_score_api_sim_score_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Score"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
